/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
#define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
#define _NAMESPACE_CONCAT(NS, ID) NS ## ID
#define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
#define CASADI_PREFIX(ID) FORCESNLPsolver_model_12_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "FORCESNLPsolver/include/FORCESNLPsolver.h"

#define PRINTF printf
FORCESNLPsolver_float CASADI_PREFIX(sq)(FORCESNLPsolver_float x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

FORCESNLPsolver_float CASADI_PREFIX(sign)(FORCESNLPsolver_float x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const solver_int32_default CASADI_PREFIX(s0)[] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
#define s0 CASADI_PREFIX(s0)
static const solver_int32_default CASADI_PREFIX(s1)[] = {30, 1, 0, 30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};
#define s1 CASADI_PREFIX(s1)
static const solver_int32_default CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const solver_int32_default CASADI_PREFIX(s3)[] = {1, 6, 0, 1, 2, 3, 4, 5, 5, 0, 0, 0, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const solver_int32_default CASADI_PREFIX(s4)[] = {2, 1, 0, 2, 0, 1};
#define s4 CASADI_PREFIX(s4)
static const solver_int32_default CASADI_PREFIX(s5)[] = {2, 6, 0, 0, 0, 2, 4, 6, 8, 0, 1, 0, 1, 0, 1, 0, 1};
#define s5 CASADI_PREFIX(s5)
/* evaluate_stages */
solver_int32_default FORCESNLPsolver_model_12(const FORCESNLPsolver_float **arg, FORCESNLPsolver_float **res) 
{
    FORCESNLPsolver_float a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25;
    a0=arg[0] ? arg[0][3] : 0;
    a1=arg[1] ? arg[1][4] : 0;
    a1=(a0-a1);
    a2=arg[1] ? arg[1][0] : 0;
    a3=(a2*a1);
    a4=(a3*a1);
    a5=arg[0] ? arg[0][4] : 0;
    a6=arg[1] ? arg[1][5] : 0;
    a6=(a5-a6);
    a7=arg[1] ? arg[1][1] : 0;
    a8=(a7*a6);
    a9=(a8*a6);
    a4=(a4+a9);
    a9=arg[1] ? arg[1][3] : 0;
    a10=arg[0] ? arg[0][1] : 0;
    a11=(a9*a10);
    a12=(a11*a10);
    a4=(a4+a12);
    a12=10.;
    a13=arg[0] ? arg[0][2] : 0;
    a14=(a12*a13);
    a15=(a14*a13);
    a4=(a4+a15);
    a15=arg[1] ? arg[1][2] : 0;
    a16=arg[0] ? arg[0][0] : 0;
    a17=(a15*a16);
    a18=(a17*a16);
    a4=(a4+a18);
    if (res[0]!=0) res[0][0]=a4;
    a15=(a15*a16);
    a17=(a17+a15);
    if (res[1]!=0) res[1][0]=a17;
    a9=(a9*a10);
    a11=(a11+a9);
    if (res[1]!=0) res[1][1]=a11;
    a12=(a12*a13);
    a14=(a14+a12);
    if (res[1]!=0) res[1][2]=a14;
    a2=(a2*a1);
    a3=(a3+a2);
    if (res[1]!=0) res[1][3]=a3;
    a7=(a7*a6);
    a8=(a8+a7);
    if (res[1]!=0) res[1][4]=a8;
    a8=arg[0] ? arg[0][5] : 0;
    a7=cos(a8);
    a6=arg[1] ? arg[1][8] : 0;
    a7=(a7*a6);
    a0=(a0+a7);
    a7=arg[1] ? arg[1][9] : 0;
    a7=(a0-a7);
    a3=arg[1] ? arg[1][11] : 0;
    a2=cos(a3);
    a1=(a7*a2);
    a14=sin(a8);
    a14=(a14*a6);
    a5=(a5+a14);
    a14=arg[1] ? arg[1][10] : 0;
    a14=(a5-a14);
    a12=sin(a3);
    a11=(a14*a12);
    a1=(a1-a11);
    a11=arg[1] ? arg[1][12] : 0;
    a9=arg[1] ? arg[1][7] : 0;
    a11=(a11+a9);
    a11=sq(a11);
    a1=(a1/a11);
    a10=(a1*a2);
    a17=sin(a3);
    a15=(a7*a17);
    a3=cos(a3);
    a16=(a14*a3);
    a15=(a15+a16);
    a16=arg[1] ? arg[1][13] : 0;
    a16=(a16+a9);
    a16=sq(a16);
    a15=(a15/a16);
    a4=(a15*a17);
    a10=(a10+a4);
    a4=(a10*a7);
    a15=(a15*a3);
    a1=(a1*a12);
    a15=(a15-a1);
    a1=(a15*a14);
    a4=(a4+a1);
    a4=(a4+a13);
    if (res[2]!=0) res[2][0]=a4;
    a4=arg[1] ? arg[1][14] : 0;
    a0=(a0-a4);
    a4=arg[1] ? arg[1][16] : 0;
    a1=cos(a4);
    a18=(a0*a1);
    a19=arg[1] ? arg[1][15] : 0;
    a5=(a5-a19);
    a19=sin(a4);
    a20=(a5*a19);
    a18=(a18-a20);
    a20=arg[1] ? arg[1][17] : 0;
    a20=(a20+a9);
    a20=sq(a20);
    a18=(a18/a20);
    a21=(a18*a1);
    a22=sin(a4);
    a23=(a0*a22);
    a4=cos(a4);
    a24=(a5*a4);
    a23=(a23+a24);
    a24=arg[1] ? arg[1][18] : 0;
    a24=(a24+a9);
    a24=sq(a24);
    a23=(a23/a24);
    a9=(a23*a22);
    a21=(a21+a9);
    a9=(a21*a0);
    a23=(a23*a4);
    a18=(a18*a19);
    a23=(a23-a18);
    a18=(a23*a5);
    a9=(a9+a18);
    a9=(a9+a13);
    if (res[2]!=0) res[2][1]=a9;
    a9=1.;
    if (res[3]!=0) res[3][0]=a9;
    if (res[3]!=0) res[3][1]=a9;
    a9=(a2/a11);
    a13=(a2*a9);
    a18=(a17/a16);
    a25=(a17*a18);
    a13=(a13+a25);
    a13=(a7*a13);
    a13=(a13+a10);
    a18=(a3*a18);
    a9=(a12*a9);
    a18=(a18-a9);
    a18=(a14*a18);
    a13=(a13+a18);
    if (res[3]!=0) res[3][2]=a13;
    a13=(a1/a20);
    a18=(a1*a13);
    a9=(a22/a24);
    a25=(a22*a9);
    a18=(a18+a25);
    a18=(a0*a18);
    a18=(a18+a21);
    a9=(a4*a9);
    a13=(a19*a13);
    a9=(a9-a13);
    a9=(a5*a9);
    a18=(a18+a9);
    if (res[3]!=0) res[3][3]=a18;
    a18=(a3/a16);
    a9=(a17*a18);
    a13=(a12/a11);
    a25=(a2*a13);
    a9=(a9-a25);
    a9=(a7*a9);
    a18=(a3*a18);
    a13=(a12*a13);
    a18=(a18+a13);
    a18=(a14*a18);
    a18=(a18+a15);
    a9=(a9+a18);
    if (res[3]!=0) res[3][4]=a9;
    a9=(a4/a24);
    a18=(a22*a9);
    a13=(a19/a20);
    a25=(a1*a13);
    a18=(a18-a25);
    a18=(a0*a18);
    a9=(a4*a9);
    a13=(a19*a13);
    a9=(a9+a13);
    a9=(a5*a9);
    a9=(a9+a23);
    a18=(a18+a9);
    if (res[3]!=0) res[3][5]=a18;
    a18=cos(a8);
    a18=(a6*a18);
    a9=(a3*a18);
    a8=sin(a8);
    a6=(a6*a8);
    a8=(a17*a6);
    a9=(a9-a8);
    a9=(a9/a16);
    a17=(a17*a9);
    a16=(a2*a6);
    a8=(a12*a18);
    a16=(a16+a8);
    a16=(a16/a11);
    a2=(a2*a16);
    a17=(a17-a2);
    a7=(a7*a17);
    a10=(a10*a6);
    a7=(a7-a10);
    a3=(a3*a9);
    a12=(a12*a16);
    a3=(a3+a12);
    a14=(a14*a3);
    a15=(a15*a18);
    a14=(a14+a15);
    a7=(a7+a14);
    if (res[3]!=0) res[3][6]=a7;
    a7=(a4*a18);
    a14=(a22*a6);
    a7=(a7-a14);
    a7=(a7/a24);
    a22=(a22*a7);
    a24=(a1*a6);
    a14=(a19*a18);
    a24=(a24+a14);
    a24=(a24/a20);
    a1=(a1*a24);
    a22=(a22-a1);
    a0=(a0*a22);
    a21=(a21*a6);
    a0=(a0-a21);
    a4=(a4*a7);
    a19=(a19*a24);
    a4=(a4+a19);
    a5=(a5*a4);
    a23=(a23*a18);
    a5=(a5+a23);
    a0=(a0+a5);
    if (res[3]!=0) res[3][7]=a0;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_12_init(solver_int32_default *f_type, solver_int32_default *n_in, solver_int32_default *n_out, solver_int32_default *sz_arg, solver_int32_default *sz_res) 
{
    *f_type = 1;
    *n_in = 2;
    *n_out = 4;
    *sz_arg = 2;
    *sz_res = 4;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_12_sparsity(solver_int32_default i, solver_int32_default *nrow, solver_int32_default *ncol, const solver_int32_default **colind, const solver_int32_default **row) 
{
    const solver_int32_default *s;
    switch (i) 
    {
      case 0:
        s = s0;
        break;
      case 1:
        s = s1;
        break;
      case 2:
        s = s2;
        break;
      case 3:
        s = s3;
        break;
      case 4:
        s = s4;
        break;
      case 5:
        s = s5;
        break;
      default:
        return 1;
    }
    
    *nrow = s[0];
    *ncol = s[1];
    *colind = s + 2;
    *row = s + 2 + (*ncol + 1);
    return 0;
}

solver_int32_default FORCESNLPsolver_model_12_work(solver_int32_default *sz_iw, solver_int32_default *sz_w) 
{
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 26;
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
