/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
#define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
#define _NAMESPACE_CONCAT(NS, ID) NS ## ID
#define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
#define CASADI_PREFIX(ID) FORCESNLPsolver_model_1_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "FORCESNLPsolver/include/FORCESNLPsolver.h"

#define PRINTF printf
FORCESNLPsolver_float CASADI_PREFIX(sq)(FORCESNLPsolver_float x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

FORCESNLPsolver_float CASADI_PREFIX(sign)(FORCESNLPsolver_float x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const solver_int32_default CASADI_PREFIX(s0)[] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
#define s0 CASADI_PREFIX(s0)
static const solver_int32_default CASADI_PREFIX(s1)[] = {40, 1, 0, 40, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
#define s1 CASADI_PREFIX(s1)
static const solver_int32_default CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const solver_int32_default CASADI_PREFIX(s3)[] = {1, 7, 0, 1, 2, 2, 3, 4, 4, 4, 0, 0, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const solver_int32_default CASADI_PREFIX(s4)[] = {4, 1, 0, 4, 0, 1, 2, 3};
#define s4 CASADI_PREFIX(s4)
static const solver_int32_default CASADI_PREFIX(s5)[] = {4, 7, 0, 2, 5, 6, 7, 8, 11, 12, 0, 1, 0, 1, 2, 3, 0, 1, 0, 1, 2, 3};
#define s5 CASADI_PREFIX(s5)
/* evaluate_stages */
solver_int32_default FORCESNLPsolver_model_1(const FORCESNLPsolver_float **arg, FORCESNLPsolver_float **res) 
{
    FORCESNLPsolver_float a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20;
    a0=arg[0] ? arg[0][3] : 0;
    a1=arg[1] ? arg[1][4] : 0;
    a1=(a0-a1);
    a2=arg[1] ? arg[1][0] : 0;
    a3=(a2*a1);
    a4=(a3*a1);
    a5=arg[0] ? arg[0][4] : 0;
    a6=arg[1] ? arg[1][5] : 0;
    a6=(a5-a6);
    a7=arg[1] ? arg[1][1] : 0;
    a8=(a7*a6);
    a9=(a8*a6);
    a4=(a4+a9);
    a9=arg[0] ? arg[0][0] : 0;
    a10=arg[1] ? arg[1][6] : 0;
    a11=(a9-a10);
    a12=arg[1] ? arg[1][2] : 0;
    a11=(a12*a11);
    a10=(a9-a10);
    a13=(a11*a10);
    a4=(a4+a13);
    a13=arg[1] ? arg[1][3] : 0;
    a14=arg[0] ? arg[0][1] : 0;
    a15=(a13*a14);
    a16=(a15*a14);
    a4=(a4+a16);
    if (res[0]!=0) res[0][0]=a4;
    a12=(a12*a10);
    a11=(a11+a12);
    if (res[1]!=0) res[1][0]=a11;
    a13=(a13*a14);
    a15=(a15+a13);
    if (res[1]!=0) res[1][1]=a15;
    a2=(a2*a1);
    a3=(a3+a2);
    if (res[1]!=0) res[1][2]=a3;
    a7=(a7*a6);
    a8=(a8+a7);
    if (res[1]!=0) res[1][3]=a8;
    a8=arg[0] ? arg[0][5] : 0;
    a7=cos(a8);
    a6=(a9*a7);
    a3=2.0000000000000001e-01;
    a2=(a3*a14);
    a2=(a8+a2);
    a1=cos(a2);
    a15=(a9*a1);
    a13=2.;
    a15=(a13*a15);
    a6=(a6+a15);
    a15=(a3*a14);
    a15=(a8+a15);
    a11=cos(a15);
    a12=(a9*a11);
    a12=(a13*a12);
    a6=(a6+a12);
    a12=4.0000000000000002e-01;
    a10=(a12*a14);
    a10=(a8+a10);
    a4=cos(a10);
    a16=(a9*a4);
    a6=(a6+a16);
    a16=6.6666666666666666e-02;
    a6=(a16*a6);
    a0=(a0+a6);
    if (res[2]!=0) res[2][0]=a0;
    a0=sin(a8);
    a6=(a9*a0);
    a17=sin(a2);
    a18=(a9*a17);
    a18=(a13*a18);
    a6=(a6+a18);
    a18=sin(a15);
    a19=(a9*a18);
    a19=(a13*a19);
    a6=(a6+a19);
    a19=sin(a10);
    a20=(a9*a19);
    a6=(a6+a20);
    a6=(a16*a6);
    a5=(a5+a6);
    if (res[2]!=0) res[2][1]=a5;
    a5=(a13*a14);
    a5=(a14+a5);
    a6=(a13*a14);
    a5=(a5+a6);
    a5=(a5+a14);
    a5=(a16*a5);
    a5=(a8+a5);
    if (res[2]!=0) res[2][2]=a5;
    a5=arg[0] ? arg[0][2] : 0;
    a14=(a13*a5);
    a14=(a5+a14);
    a6=(a13*a5);
    a14=(a14+a6);
    a14=(a14+a5);
    a14=(a16*a14);
    a5=arg[0] ? arg[0][6] : 0;
    a5=(a5+a14);
    if (res[2]!=0) res[2][3]=a5;
    a1=(a13*a1);
    a7=(a7+a1);
    a11=(a13*a11);
    a7=(a7+a11);
    a7=(a7+a4);
    a7=(a16*a7);
    if (res[3]!=0) res[3][0]=a7;
    a17=(a13*a17);
    a0=(a0+a17);
    a18=(a13*a18);
    a0=(a0+a18);
    a0=(a0+a19);
    a0=(a16*a0);
    if (res[3]!=0) res[3][1]=a0;
    a0=sin(a2);
    a19=(a3*a0);
    a19=(a9*a19);
    a19=(a13*a19);
    a18=sin(a15);
    a17=(a3*a18);
    a17=(a9*a17);
    a17=(a13*a17);
    a19=(a19+a17);
    a17=sin(a10);
    a7=(a12*a17);
    a7=(a9*a7);
    a19=(a19+a7);
    a19=(a16*a19);
    a19=(-a19);
    if (res[3]!=0) res[3][2]=a19;
    a2=cos(a2);
    a19=(a3*a2);
    a19=(a9*a19);
    a19=(a13*a19);
    a15=cos(a15);
    a3=(a3*a15);
    a3=(a9*a3);
    a3=(a13*a3);
    a19=(a19+a3);
    a10=cos(a10);
    a3=(a12*a10);
    a3=(a9*a3);
    a19=(a19+a3);
    a19=(a16*a19);
    if (res[3]!=0) res[3][3]=a19;
    if (res[3]!=0) res[3][4]=a12;
    if (res[3]!=0) res[3][5]=a12;
    a12=1.;
    if (res[3]!=0) res[3][6]=a12;
    if (res[3]!=0) res[3][7]=a12;
    a19=sin(a8);
    a19=(a9*a19);
    a0=(a9*a0);
    a0=(a13*a0);
    a19=(a19+a0);
    a18=(a9*a18);
    a18=(a13*a18);
    a19=(a19+a18);
    a17=(a9*a17);
    a19=(a19+a17);
    a19=(a16*a19);
    a19=(-a19);
    if (res[3]!=0) res[3][8]=a19;
    a8=cos(a8);
    a8=(a9*a8);
    a2=(a9*a2);
    a2=(a13*a2);
    a8=(a8+a2);
    a15=(a9*a15);
    a13=(a13*a15);
    a8=(a8+a13);
    a9=(a9*a10);
    a8=(a8+a9);
    a16=(a16*a8);
    if (res[3]!=0) res[3][9]=a16;
    if (res[3]!=0) res[3][10]=a12;
    if (res[3]!=0) res[3][11]=a12;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_init(solver_int32_default *f_type, solver_int32_default *n_in, solver_int32_default *n_out, solver_int32_default *sz_arg, solver_int32_default *sz_res) 
{
    *f_type = 1;
    *n_in = 2;
    *n_out = 4;
    *sz_arg = 2;
    *sz_res = 4;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_sparsity(solver_int32_default i, solver_int32_default *nrow, solver_int32_default *ncol, const solver_int32_default **colind, const solver_int32_default **row) 
{
    const solver_int32_default *s;
    switch (i) 
    {
      case 0:
        s = s0;
        break;
      case 1:
        s = s1;
        break;
      case 2:
        s = s2;
        break;
      case 3:
        s = s3;
        break;
      case 4:
        s = s4;
        break;
      case 5:
        s = s5;
        break;
      default:
        return 1;
    }
    
    *nrow = s[0];
    *ncol = s[1];
    *colind = s + 2;
    *row = s + 2 + (*ncol + 1);
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_work(solver_int32_default *sz_iw, solver_int32_default *sz_w) 
{
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 21;
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
