/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
#define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
#define _NAMESPACE_CONCAT(NS, ID) NS ## ID
#define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
#define CASADI_PREFIX(ID) FORCESNLPsolver_model_1_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "FORCESNLPsolver/include/FORCESNLPsolver.h"

#define PRINTF printf
FORCESNLPsolver_float CASADI_PREFIX(sq)(FORCESNLPsolver_float x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

FORCESNLPsolver_float CASADI_PREFIX(sign)(FORCESNLPsolver_float x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const solver_int32_default CASADI_PREFIX(s0)[] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
#define s0 CASADI_PREFIX(s0)
static const solver_int32_default CASADI_PREFIX(s1)[] = {0, 1, 0, 0};
#define s1 CASADI_PREFIX(s1)
static const solver_int32_default CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const solver_int32_default CASADI_PREFIX(s3)[] = {1, 5, 0, 1, 2, 2, 2, 2, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const solver_int32_default CASADI_PREFIX(s4)[] = {3, 1, 0, 3, 0, 1, 2};
#define s4 CASADI_PREFIX(s4)
static const solver_int32_default CASADI_PREFIX(s5)[] = {3, 5, 0, 2, 4, 7, 9, 12, 0, 1, 0, 1, 0, 1, 2, 0, 1, 0, 1, 2};
#define s5 CASADI_PREFIX(s5)
/* evaluate_stages */
solver_int32_default FORCESNLPsolver_model_1(const FORCESNLPsolver_float **arg, FORCESNLPsolver_float **res) 
{
    FORCESNLPsolver_float a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35;
    a0=arg[0] ? arg[0][0] : 0;
    a1=sq(a0);
    a2=arg[0] ? arg[0][1] : 0;
    a3=sq(a2);
    a1=(a1+a3);
    if (res[0]!=0) res[0][0]=a1;
    a1=(a0+a0);
    if (res[1]!=0) res[1][0]=a1;
    a1=(a2+a2);
    if (res[1]!=0) res[1][1]=a1;
    a1=arg[0] ? arg[0][4] : 0;
    a3=(a1*a2);
    a4=arg[0] ? arg[0][2] : 0;
    a5=cos(a4);
    a6=arg[0] ? arg[0][3] : 0;
    a7=(a6*a5);
    a3=(a3+a7);
    a7=(a1*a0);
    a8=sin(a4);
    a9=(a6*a8);
    a7=(a7-a9);
    a9=5.0000000000000003e-02;
    a10=(a9*a7);
    a10=(a2+a10);
    a11=(a1*a10);
    a12=(a9*a1);
    a12=(a4-a12);
    a13=cos(a12);
    a14=(a6*a13);
    a11=(a11+a14);
    a14=2.;
    a15=(a14*a11);
    a15=(a3+a15);
    a3=(a9*a3);
    a3=(a0-a3);
    a16=(a1*a3);
    a17=sin(a12);
    a18=(a6*a17);
    a16=(a16-a18);
    a18=(a9*a16);
    a18=(a2+a18);
    a19=(a1*a18);
    a20=(a9*a1);
    a20=(a4-a20);
    a21=cos(a20);
    a22=(a6*a21);
    a19=(a19+a22);
    a22=(a14*a19);
    a15=(a15+a22);
    a11=(a9*a11);
    a11=(a0-a11);
    a22=(a1*a11);
    a23=sin(a20);
    a24=(a6*a23);
    a22=(a22-a24);
    a24=1.0000000000000001e-01;
    a25=(a24*a22);
    a25=(a2+a25);
    a26=(a1*a25);
    a27=(a24*a1);
    a27=(a4-a27);
    a28=cos(a27);
    a29=(a6*a28);
    a26=(a26+a29);
    a15=(a15+a26);
    a26=1.6666666666666666e-02;
    a15=(a26*a15);
    a15=(a0-a15);
    if (res[2]!=0) res[2][0]=a15;
    a16=(a14*a16);
    a7=(a7+a16);
    a22=(a14*a22);
    a7=(a7+a22);
    a19=(a24*a19);
    a19=(a0-a19);
    a22=(a1*a19);
    a16=sin(a27);
    a15=(a6*a16);
    a22=(a22-a15);
    a7=(a7+a22);
    a7=(a26*a7);
    a7=(a2+a7);
    if (res[2]!=0) res[2][1]=a7;
    a7=(a14*a1);
    a7=(a1+a7);
    a22=(a14*a1);
    a7=(a7+a22);
    a7=(a7+a1);
    a7=(a26*a7);
    a7=(a4-a7);
    if (res[2]!=0) res[2][2]=a7;
    a7=(a9*a1);
    a7=(a1*a7);
    a22=(a14*a7);
    a15=(a9*a1);
    a15=(a1*a15);
    a29=(a14*a15);
    a22=(a22+a29);
    a7=(a9*a7);
    a29=1.;
    a7=(a29-a7);
    a7=(a1*a7);
    a30=(a24*a7);
    a30=(a1*a30);
    a22=(a22+a30);
    a22=(a26*a22);
    a22=(a29-a22);
    if (res[3]!=0) res[3][0]=a22;
    a22=(a14*a1);
    a22=(a1+a22);
    a7=(a14*a7);
    a22=(a22+a7);
    a15=(a24*a15);
    a15=(a29-a15);
    a15=(a1*a15);
    a22=(a22+a15);
    a22=(a26*a22);
    if (res[3]!=0) res[3][1]=a22;
    a22=(a14*a1);
    a22=(a1+a22);
    a15=(a9*a1);
    a15=(a1*a15);
    a7=(a9*a15);
    a7=(a29-a7);
    a7=(a1*a7);
    a30=(a14*a7);
    a22=(a22+a30);
    a30=(a9*a1);
    a30=(a1*a30);
    a31=(a24*a30);
    a31=(a29-a31);
    a31=(a1*a31);
    a22=(a22+a31);
    a22=(a26*a22);
    a22=(-a22);
    if (res[3]!=0) res[3][2]=a22;
    a15=(a14*a15);
    a30=(a14*a30);
    a15=(a15+a30);
    a7=(a24*a7);
    a7=(a1*a7);
    a15=(a15+a7);
    a15=(a26*a15);
    a15=(a29-a15);
    if (res[3]!=0) res[3][3]=a15;
    a15=sin(a4);
    a15=(a6*a15);
    a7=(a9*a15);
    a7=(a1*a7);
    a30=cos(a12);
    a22=(a6*a30);
    a7=(a7-a22);
    a22=(a9*a7);
    a22=(a1*a22);
    a31=sin(a20);
    a32=(a6*a31);
    a22=(a22-a32);
    a32=(a14*a22);
    a4=cos(a4);
    a4=(a6*a4);
    a33=(a9*a4);
    a33=(a1*a33);
    a12=sin(a12);
    a34=(a6*a12);
    a33=(a33+a34);
    a34=(a14*a33);
    a15=(a15+a34);
    a32=(a32-a15);
    a33=(a9*a33);
    a33=(a1*a33);
    a20=cos(a20);
    a15=(a6*a20);
    a33=(a33-a15);
    a15=(a24*a33);
    a15=(a1*a15);
    a34=sin(a27);
    a35=(a6*a34);
    a15=(a15-a35);
    a32=(a32+a15);
    a32=(a26*a32);
    a32=(-a32);
    if (res[3]!=0) res[3][4]=a32;
    a7=(a14*a7);
    a7=(a7-a4);
    a33=(a14*a33);
    a7=(a7+a33);
    a22=(a24*a22);
    a22=(a1*a22);
    a27=cos(a27);
    a33=(a6*a27);
    a22=(a22+a33);
    a7=(a7-a22);
    a7=(a26*a7);
    if (res[3]!=0) res[3][5]=a7;
    if (res[3]!=0) res[3][6]=a29;
    a29=(a9*a8);
    a29=(a1*a29);
    a13=(a13-a29);
    a29=(a14*a13);
    a29=(a5+a29);
    a5=(a9*a5);
    a5=(a1*a5);
    a5=(a5+a17);
    a17=(a9*a5);
    a17=(a1*a17);
    a21=(a21-a17);
    a17=(a14*a21);
    a29=(a29+a17);
    a13=(a9*a13);
    a13=(a1*a13);
    a13=(a13+a23);
    a23=(a24*a13);
    a23=(a1*a23);
    a28=(a28-a23);
    a29=(a29+a28);
    a29=(a26*a29);
    a29=(-a29);
    if (res[3]!=0) res[3][7]=a29;
    a5=(a14*a5);
    a8=(a8+a5);
    a13=(a14*a13);
    a8=(a8+a13);
    a21=(a24*a21);
    a21=(a1*a21);
    a21=(a21+a16);
    a8=(a8+a21);
    a8=(a26*a8);
    a8=(-a8);
    if (res[3]!=0) res[3][8]=a8;
    a8=(a9*a0);
    a8=(a1*a8);
    a10=(a10+a8);
    a8=-5.0000000000000003e-02;
    a12=(a8*a12);
    a12=(a6*a12);
    a10=(a10-a12);
    a12=(a14*a10);
    a12=(a2+a12);
    a2=(a9*a2);
    a2=(a1*a2);
    a3=(a3-a2);
    a30=(a8*a30);
    a30=(a6*a30);
    a3=(a3-a30);
    a30=(a9*a3);
    a30=(a1*a30);
    a18=(a18+a30);
    a31=(a8*a31);
    a31=(a6*a31);
    a18=(a18-a31);
    a31=(a14*a18);
    a12=(a12+a31);
    a9=(a9*a10);
    a9=(a1*a9);
    a11=(a11-a9);
    a8=(a8*a20);
    a8=(a6*a8);
    a11=(a11-a8);
    a8=(a24*a11);
    a8=(a1*a8);
    a25=(a25+a8);
    a8=-1.0000000000000001e-01;
    a34=(a8*a34);
    a34=(a6*a34);
    a25=(a25-a34);
    a12=(a12+a25);
    a12=(a26*a12);
    a12=(-a12);
    if (res[3]!=0) res[3][9]=a12;
    a3=(a14*a3);
    a0=(a0+a3);
    a14=(a14*a11);
    a0=(a0+a14);
    a24=(a24*a18);
    a1=(a1*a24);
    a19=(a19-a1);
    a27=(a8*a27);
    a6=(a6*a27);
    a19=(a19-a6);
    a0=(a0+a19);
    a26=(a26*a0);
    if (res[3]!=0) res[3][10]=a26;
    if (res[3]!=0) res[3][11]=a8;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_init(solver_int32_default *f_type, solver_int32_default *n_in, solver_int32_default *n_out, solver_int32_default *sz_arg, solver_int32_default *sz_res) 
{
    *f_type = 1;
    *n_in = 2;
    *n_out = 4;
    *sz_arg = 2;
    *sz_res = 4;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_sparsity(solver_int32_default i, solver_int32_default *nrow, solver_int32_default *ncol, const solver_int32_default **colind, const solver_int32_default **row) 
{
    const solver_int32_default *s;
    switch (i) 
    {
      case 0:
        s = s0;
        break;
      case 1:
        s = s1;
        break;
      case 2:
        s = s2;
        break;
      case 3:
        s = s3;
        break;
      case 4:
        s = s4;
        break;
      case 5:
        s = s5;
        break;
      default:
        return 1;
    }
    
    *nrow = s[0];
    *ncol = s[1];
    *colind = s + 2;
    *row = s + 2 + (*ncol + 1);
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_work(solver_int32_default *sz_iw, solver_int32_default *sz_w) 
{
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 36;
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
